---
- name: Install useful tools
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - htop
    - vim

- name: Copy vagrant authorized keys to root
  copy:
    src: /home/vagrant/.ssh
    dest: /root/
    remote_src: yes
