---
- name: Install packer and qemu
  package:
    name:
      - packer
      - qemu-system

- name: Create data directory
  file:
    path: /data
    state: directory
    owner: vagrant
    group: vagrant

- name: Upload templates
  synchronize:
    src: files/templates
    dest: /data/
  become: false

- name: Build Windows XP
  include: build.yml
  loop:
    - { name: 'winxp', ram: '512', packer_template: 'windows.json', packer_varfile: 'winxp.json' }
  when: enabled_vms['winxp']

- name: Build Windows 7
  include: build.yml
  loop:
    - { name: 'win7', ram: '1500', packer_template: 'windows.json', packer_varfile: 'win7.json' }
  when: enabled_vms['win7']

- name: Build Ubuntu
  include: build.yml
  loop:
    - { name: 'ubuntu', ram: '1024', packer_template: 'ubuntu.json', packer_varfile: 'ubuntu-16.04-server-i386.json' }
  when: enabled_vms['ubuntu']
