---
- name: Test Xen hypervisor
  slurp:
    src: /sys/hypervisor/type
  register: hypertype
  changed_when: false
  failed_when: hypertype['content'] | b64decode | trim != "xen"

- name: Get xen version
  shell: xl info | grep xen_version
  register: xen_version
  changed_when: false

- name: Display xen version
  debug:
    var: xen_version.stdout
