---
- name: Ensure apt-src is installed
  package:
    name: apt-src

- name: Dirty hack to make dpkg ignore missing dependency info while building
  replace:
    path: '/usr/bin/dpkg-shlibdeps'
    regexp: '^my \$ignore_missing_info = 0;'
    replace: 'my $ignore_missing_info = 1;'

- name: Update apt-src cache
  command: apt-src update

#- name: Download, build and install libvirt sources
#  command: apt-src -i install libvirt-daemon-system

- name: Download libvirt sources
  command: apt-src install libvirt-daemon-system

- name: Build libvirt sources
  command: apt-src build libvirt-daemon-system

- name: Install libvirt sources
  shell: dpkg --install libvirt*.deb

- name: Prevent libvirt from being upgraded accidentally
  command: apt-mark hold libvirt-daemon-system
