---
- name: Install development tools
  dnf:
    name: '@development-tools'
    state: present

- name: Clone Xen source code
  git:
    repo: 'git://xenbits.xen.org/xen.git'
    dest: /home/vagrant/xen
    version: "{{ xen_src_version }}"
  become: false
  register: git_xen

- name: Build and intall Xen from source
  when: xen_build_force or git_xen is changed
  block:
    - name: Install Xen build dependencies with builddep
      command: dnf builddep -y xen-devel kernel
      args:
        warn: false

    - name: Install extra Xen build dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - dev86
        - glib2-devel
        - pixman-devel
        - glibc-devel.i686

    - name: Configure Xen
      command: ./configure --prefix=/usr --libdir=/usr/lib64 --enable-systemd
      args:
        chdir: /home/vagrant/xen
      become: false

    - name: Build Xen
      command: "make -j{{ ansible_processor_vcpus }} dist"
      args:
        chdir: /home/vagrant/xen
      become: false

    - name: Install Xen
      command: make install
      args:
        chdir: /home/vagrant/xen

    - name: Rebuild dynamic linker cache
      command: /sbin/ldconfig

    - name: Update GRUB2
      command: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: Update GRUB to boot on Xen kernel by default
      command: grub2-set-default 'Fedora, with Xen hypervisor'

    - name: Install chkconfig for SysV backwards compatibility
      package:
        name: chkconfig
        state: present

    - name: Enable Xen system services
      service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - xen-init-dom0.service
        - xendomains.service
        - xenconsoled.service
        - xenstored.service

    - name: Reboot
      reboot:
