---
- name: install Xen package
  package:
    name: xen
    state: present
  register: xen_package
  notify:
    - Reboot

- name: update GRUB to boot on Xen kernel by default
  command: grub2-set-default 'Fedora, with Xen hypervisor'
  when: xen_package is changed
